
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

###  Registro de usuario anonimos

POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@mail.com",
    "password" : "admin54321",
    "c_password" : "admin54321"
}
### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 47|tWrnce9nyjXed7HKIiOzomyL3C6bM1PER1arDhC48d93b340

POST  http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 15|nigyd03NQoPCddmiyp6Ya60TaWJTGZh5HtS7d4dh15c1c68e
