GET  http://127.0.0.1:8000/api/usuario

### guardar  usuario

POST http://127.0.0.1:8000/api/usuario
Content-Type:  application/json

{
    "name": "maria",
    "email": "maria@mail.com",
    "password": "maria54321"
}

### mostrar
GET http://127.0.0.1:8000/api/usuario/3

### Modificar

PUT http://127.0.0.1:8000/api/usuario/3
Accept: application/json
Content-Type:  application/json

{
    "name": "lupita",
    "email": "lupita@mail.com",
    "password": "lupita54321"
}

### eliminar

DELETE http://127.0.0.1:8000/api/usuario/2
Accept: application/json
